services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: athiloka-web
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
